build_dir: 8-post-synth-power-analysis
build_id: '8'
commands:
- source run.sh
debug:
- source debug.sh
edges_i:
  adk:
  - f: adk
    step: 2-freepdk-45nm
  design.sdc:
  - f: design.sdc
    step: 4-brg-synopsys-dc-synthesis
  design.spef.gz:
  - f: design.spef.gz
    step: 4-brg-synopsys-dc-synthesis
  design.vcs.v:
  - f: design.vcs.v
    step: 4-brg-synopsys-dc-synthesis
  saif:
  - f: saif
    step: 6-post-synth-gate-level-simulation
  vcd:
  - f: vcd
    step: 6-post-synth-gate-level-simulation
edges_o:
  power.summary.txt:
  - f: powerFF.summary.txt
    step: 10-brg-synth-flow-summary
  - f: powerFF.summary.txt
    step: 12-brg-flow-summary
inputs:
- adk
- design.vcs.v
- design.sdc
- design.spef.gz
- saif
- vcd
- design.namemap
name: post-synth-power-analysis
outputs:
- primetime.session
- design.sdf
- power.summary.txt
parameters:
  analysis_mode: averaged
  clock_period: 3.0
  design_name: ProcDpathAluWrapper
  extra_link_lib_dir: ./inputs/adk
  lib_op_condition: undefined
  order:
  - designer-interface.tcl
  - setup-session.tcl
  - read-design.tcl
  - report-timing.tcl
  - report-power.tcl
  power_analysis_on_tests: false
  saif_instance: ProcDpathAluWrapper_tb/DUT
  zero_delay_simulation: true
source: /classes/ece5745/install/venv-pkgs/x86_64-rhel7/pypy3-pymtl3-7.3.3/site-packages/steps/brg-synopsys-pt-power
