#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-debug
#=========================================================================
# Generator : /classes/ece5745/install/venv-pkgs/x86_64-rhel7/pypy3-pymtl3-7.3.3/site-packages/mflowgen/core/build_orchestrator.py

# Pre

export design_name=ProcDpathAluWrapper
export saif_instance=ProcDpathAluWrapper_tb/DUT
export analysis_mode=averaged
export zero_delay_simulation=True
export lib_op_condition=undefined
export extra_link_lib_dir=./inputs/adk
export power_analysis_on_tests=False
export clock_period=3.0
export order=designer-interface.tcl,setup-session.tcl,read-design.tcl,report-timing.tcl,report-power.tcl

# Debug

source debug.sh

