build_dir: 6-post-synth-gate-level-simulation
build_id: '6'
commands:
- ./run.sh
edges_i:
  adk:
  - f: adk
    step: 2-freepdk-45nm
  design.vcs.v:
  - f: design.vcs.v
    step: 4-brg-synopsys-dc-synthesis
  rtl:
  - f: rtl
    step: 1-ece5745-block-gather
  testbenches:
  - f: testbenches
    step: 1-ece5745-block-gather
edges_o:
  saif:
  - f: saif
    step: 8-post-synth-power-analysis
  sim.summary.txt:
  - f: ff.summary.txt
    step: 10-brg-synth-flow-summary
  - f: ff.summary.txt
    step: 12-brg-flow-summary
  vcd:
  - f: vcd
    step: 8-post-synth-power-analysis
inputs:
- adk
- testbenches
- macrofiles
- rtl
- design.vcs.v
- design.sdf
- design.args
name: post-synth-gate-level-simulation
outputs:
- vpd
- vcd
- saif
- sim.summary.txt
parameters:
  change_clock_period: undefined
  clock_period: 3.0
  debug: false
  design_name: ProcDpathAluWrapper
  dut_name: DUT
  extra_link_lib_dir: ./inputs/adk
  input_delay: 0.05
  output_delay: 0.05
  pad_ring: false
  simtype: gate-level
  test_design_name: ProcDpathAluWrapper
  waveform: true
source: /classes/ece5745/install/venv-pkgs/x86_64-rhel7/pypy3-pymtl3-7.3.3/site-packages/steps/brg-synopsys-vcs-sim
