build_dir: 4-brg-synopsys-dc-synthesis
build_id: '4'
commands:
- bash run.sh
debug:
- export DC_EXIT_AFTER_SETUP=1
- ln -sf results/*.mapped.ddc debug.ddc
- design_vision-xg -topographical -x "source START.tcl; read_ddc debug.ddc"
edges_i:
  adk:
  - f: adk
    step: 2-freepdk-45nm
  rtl:
  - f: rtl
    step: 1-ece5745-block-gather
edges_o:
  design.sdc:
  - f: design.sdc
    step: 5-brg-cadence-innovus-init
  - f: design.sdc
    step: 7-brg-cadence-innovus-blocksetup
  - f: design.sdc
    step: 9-brg-cadence-innovus-pnr
  - f: design.sdc
    step: 11-brg-cadence-innovus-signoff
  - f: design.sdc
    step: 8-post-synth-power-analysis
  design.spef.gz:
  - f: design.spef.gz
    step: 8-post-synth-power-analysis
  design.v:
  - f: design.v
    step: 5-brg-cadence-innovus-init
  design.vcs.v:
  - f: design.vcs.v
    step: 6-post-synth-gate-level-simulation
  - f: design.vcs.v
    step: 8-post-synth-power-analysis
  synth.summary.txt:
  - f: synth.summary.txt
    step: 10-brg-synth-flow-summary
inputs:
- adk
- rtl
- run.saif
name: brg-synopsys-dc-synthesis
outputs:
- design.v
- design.vcs.v
- design.sdc
- design.namemap
- design.svf
- design.spef.gz
- synth.summary.txt
parameters:
  clk_port: clk
  clock_period: 3.0
  design_name: ProcDpathAluWrapper
  extra_link_lib_dir: ./inputs/adk
  flatten_effort: 0
  gate_clock: true
  high_effort_area_opt: false
  input_delay: 0.05
  nthreads: 16
  order:
  - designer-interface.tcl
  - setup-session.tcl
  - read-design.tcl
  - constraints.tcl
  - make-path-groups.tcl
  - compile-options.tcl
  - compile.tcl
  - generate-results.tcl
  - reporting.tcl
  output_delay: 0.05
  reset_port: reset
  reset_port2: undefined
  saif_instance: ProcDpathAluWrapper_tb/DUT
  suppress_msg: false
  suppressed_msg:
  - TFCHK-072
  - TFCHK-014
  - TFCHK-049
  - TFCHK-050
  - TFCHK-012
  - TFCHK-073
  - TFCHK-092
  - PSYN-651
  - PSYN-650
  topographical: false
  uniquify_with_design_name: true
postconditions:
- assert File( 'outputs/design.v' )
- assert File( 'outputs/design.sdc' )
- assert 'error:' not in File( 'logs/dc.log' )
- assert 'Unresolved references' not in File( 'logs/dc.log' )
- assert 'Unable to resolve' not in File( 'logs/dc.log' )
- assert 'Presto compilation terminated' not in File( 'logs/dc.log' )
- assert 'GTECH' not in File( 'outputs/design.v' )
- assert 'ELAB-405' not in File( 'logs/dc.log' ), "Multiply driven nets found in the
  design"
- assert 'ELAB-974' not in File( 'logs/dc.log' ), "Inferred latch(es) found inside
  an always_comb block in the design"
- assert 'ELAB-978' not in File( 'logs/dc.log' ), "Inferred latch(es) found inside
  an always_ff block in the design"
- assert 'PSYN-024' not in File( 'logs/dc.log' )
- assert 'PSYN-025' not in File( 'logs/dc.log' )
- assert 'PSYN-039' not in File( 'logs/dc.log' )
- assert 'create_clock' in File( 'outputs/design.sdc' )
preconditions:
- assert Tool( 'dc_shell-xg-t' )
- assert File( 'inputs/adk' )
- assert File( 'inputs/rtl' )
source: /classes/ece5745/install/venv-pkgs/x86_64-rhel7/pypy3-pymtl3-7.3.3/site-packages/steps/brg-synopsys-dc-synthesis
