#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /classes/ece5745/install/venv-pkgs/x86_64-rhel7/pypy3-pymtl3-7.3.3/site-packages/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD
export design_name='ProcDpathAluWrapper'
export clock_period=3.0
export clk_port='clk'
export reset_port='reset'
export reset_port2='undefined'
export input_delay=0.05
export output_delay=0.05
export extra_link_lib_dir='./inputs/adk'
export saif_instance='ProcDpathAluWrapper_tb/DUT'
export flatten_effort=0
export topographical=False
export nthreads=16
export high_effort_area_opt=False
export gate_clock=True
export uniquify_with_design_name=True
export suppress_msg=False
export suppressed_msg=TFCHK-072,TFCHK-014,TFCHK-049,TFCHK-050,TFCHK-012,TFCHK-073,TFCHK-092,PSYN-651,PSYN-650
export order=designer-interface.tcl,setup-session.tcl,read-design.tcl,constraints.tcl,make-path-groups.tcl,compile-options.tcl,compile.tcl,generate-results.tcl,reporting.tcl

# Commands

bash run.sh

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

