build_dir: 7-brg-cadence-innovus-blocksetup
build_id: '7'
commands:
- bash run.sh
edges_i:
  adk:
  - f: adk
    step: 2-freepdk-45nm
  design.checkpoint:
  - f: design.checkpoint
    step: 5-brg-cadence-innovus-init
  design.sdc:
  - f: design.sdc
    step: 4-brg-synopsys-dc-synthesis
edges_o:
  design.checkpoint:
  - f: design.checkpoint
    step: 9-brg-cadence-innovus-pnr
inputs:
- adk
- design.sdc
- design.checkpoint
name: brg-cadence-innovus-blocksetup
outputs:
- design.checkpoint
parameters:
  aspect_ratio: 1.0
  design_name: ProcDpathAluWrapper
  order:
  - main.tcl
postconditions:
- assert File( 'outputs/design.checkpoint' )
- assert '(IMPOPT-665)'    not in File( 'logs/run.log' )
- assert '(IMPVFC-97)'     not in File( 'logs/run.log' )
- assert '(IMPOGDS-217)'   not in File( 'logs/run.log' )
- assert '(IMPFP-53)'      not in File( 'logs/run.log' )
- assert '(IMPREPO-214)'   not in File( 'logs/run.log' )
- assert '(NRIG-39)'       not in File( 'logs/run.log' )
- assert '(NRDB-1005)'     not in File( 'logs/run.log' )
- assert '(IMPCCOPT-2215)' not in File( 'logs/run.log' )
preconditions:
- assert Tool( 'innovus' )
- assert File( 'inputs/adk' )
- assert File( 'inputs/design.sdc' )
- assert File( 'inputs/design.checkpoint/save.enc')
source: /classes/ece5745/install/venv-pkgs/x86_64-rhel7/pypy3-pymtl3-7.3.3/site-packages/steps/brg-cadence-innovus-blocksetup
