#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /classes/ece5745/install/venv-pkgs/x86_64-rhel7/pypy3-pymtl3-7.3.3/site-packages/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD
export design_name='ProcDpathAluWrapper'
export clock_period=3.0
export construct_path='/home/ezw2/ece5745/ASIC_final_subword/asic/final_proj_ALU/flow.py'
export adk='freepdk-45nm'
export adk_view='stdview'

# Commands

echo "Design name      -- ProcDpathAluWrapper"
echo "Clock period     -- 3.0"
echo "ADK              -- freepdk-45nm"
echo "ADK view         -- stdview"
echo
echo "Constructed from -- /home/ezw2/ece5745/ASIC_final_subword/asic/final_proj_ALU/flow.py"
echo

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

